name: Micrabotデプロイ

on:
  workflow_dispatch:  # 手動実行用
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v3
      
      - name: Pythonのセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: 依存関係のインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Micrabotの実行
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_INSTANCE_ID: ${{ secrets.AWS_INSTANCE_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DISCORD_MINECRAFT_TOKEN: ${{ secrets.DISCORD_MINECRAFT_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          python micrabot.py